fixtures:
  repositories:
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    inifile:
      repo: https://github.com/puppetlabs/puppetlabs-inifile.git
    mysql: 
      repo: https://github.com/puppetlabs/puppetlabs-mysql.git
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall.git
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    epel:
      repo: https://github.com/stahnma/puppet-module-epel.git
    autofs:
      repo: https://github.com/voxpupuli/puppet-autofs
  symlinks:
    osg: "#{source_dir}"
