name    'treydock-osg'
version '0.0.2'
source 'git://github.com/treydock/puppet-osg.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'OSG module'
description 'OSG module'
project_page 'http://github.com/treydock/puppet-osg'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/mysql', '~>0.6.1'
dependency 'stahman/epel', '~>0.0.3'